# Generated by Django 5.0.7 on 2024-07-23 14:57

import social_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_api", "0003_alter_like_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=social_api.models.post_image_file_path
            ),
        ),
    ]
