# Generated by Django 5.0.7 on 2024-07-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_api", "0004_post_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
